### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by bbvdhoorn** [jfq3/ggordiplots#8]
Hi,

I keep having issues with installing ggordiplots. I am probably doing something wrong.

> install_github("jfq3/ggordiplots")

This gives the following error message: Downloading GitHub repo jfq3/ggordiplots@HEAD 
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/jfq3/ggordiplots/tarball/HEAD'

Is there a work around?

Best,
Berry van der Hoorn

**Comment by jfq3** [comment]
I don’t know what the issue is. I just reinstalled without any problem. A Google search showed it was a common problem last year. I found one solution at https://github.com/yihui/xaringan/issues/199 for installing a different package:

remove.packages(c("curl","httr"))
install.packages(c("curl", "httr"))
Sys.setenv(CURL_CA_BUNDLE="/usr/lib64/microsoft-r/3.4/lib64/R/lib/microsoft-r-cacert.pem")
devtools::install_git("https://github.com/yihui/xaringan")

Don’t know if it will work for you. If you try it, let me know whether or not it works. I remember once having to reinstall devtools.
If you are using Windows, you can install ggordiplots using the attached zip file.

JQ

**Comment by bbvdhoorn** [comment]
Hi JQ,

Thanks for your reply. Unfortunately it didn't work. I do have a Windows pc
though, so the zip file would be welcome!

Best, Berry

Op ma 3 aug. 2020 om 01:38 schreef jfq3 <notifications@github.com>:
